#!/bin/sh
set -e
# Configure
printf '# Autogenerated by FDT entrypoint\n' > /etc/nginx/nginx.htpasswd
for x in $FDT_CREDENTIALS; do
  USER=$(echo "$x" | cut -d':' -f1)
  PASS=$(echo "$x" | cut -d':' -f2-)
  HASH=$(htpasswd -nb "$USER" "$PASS")

  if [ "$FDT_PLAINTEXT_CREDENTIALS" = "y" ]; then
    printf '## %s %s\n' "${USER}" "${PASS}" >> /etc/nginx/nginx.htpasswd
  else
    printf '## %s\n' "${USER}" >> /etc/nginx/nginx.htpasswd
  fi
  printf '%s\n\n' "$HASH" >> /etc/nginx/nginx.htpasswd
done
# Start nginx
exec nginx -c /etc/nginx/nginx.conf -g 'daemon off;' "$@"